name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    env:
          DETECT_BLACKDUCK_RAPID_COMPARE_MODE: BOM_COMPARE_STRICT
          #BLACKDUCK_URL: "https://sig-cons-ms-sca.app.blackduck.com/"
          #BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
          detect-version: "7.12.1"
          
    steps:
    - uses: actions/checkout@v3
    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: BlackDuck Scan
      uses: blackducksoftware/github-action@9ea442b34409737f64743781e9adc71fd8e17d38
      with:
        args: '--blackduck.url="https://sig-cons-ms-sca.app.blackduck.com" --blackduck.api.token="${{secrets.BLACKDUCK_API_TOKEN}}"'
        #args: --detect.project.name=bwapp-master --detect.tools.excluded="DETECTOR" --blackduck.trust.cert=true --detect.risk.report.pdf=true --detect.project.version.name=1
      
   # - run: ls 
#     - name: Upload Results
#       uses: actions/upload-artifact@v2
#       with:
#         name: Blackduck
#         path: /home/runner/work/insecure-bank/insecure-bank
